services:
  - type: web
    name: smartshea-backend
    env: python
    rootDir: skin-analyzer/backend
    buildCommand: |
      python -m pip install --upgrade pip
      pip install setuptools wheel
      pip install -r requirements.txt --no-cache-dir
      mkdir -p /opt/render/project/models
      cp skin_classifier_model.pth /opt/render/project/models/
      cp class_indices.npy /opt/render/project/models/
    startCommand: |
      mkdir -p models
      cp /opt/render/project/models/skin_classifier_model.pth .
      cp /opt/render/project/models/class_indices.npy .
      gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PORT
        value: 8000
      - key: PATH
        value: /opt/render/project/python/bin:${PATH}
      - key: PYTHONPATH
        value: /opt/render/project/python
      - key: GITHUB_PAGES_URL
        value: https://murayeeto.github.io
      - key: UPLOAD_FOLDER
        value: /tmp/uploads
    autoDeploy: true