services:
  - type: web
    name: smartshea-backend
    env: python
    rootDir: skin-analyzer/backend
    buildCommand: |
      python -m pip install --upgrade pip
      pip install setuptools wheel
      # Install numpy first
      pip install numpy==1.24.3 --no-cache-dir
      # Then install the rest
      pip install -r requirements.txt --no-cache-dir
      # Debug file sizes
      ls -lh skin_classifier_model.pth
      # Create model directory and copy files
      mkdir -p /opt/render/project/models
      # Use tar to preserve file permissions and attributes
      tar czf - skin_classifier_model.pth class_indices.npy | (cd /opt/render/project/models && tar xzf -)
      # Verify copied files
      ls -lh /opt/render/project/models/
      ls -la /opt/render/project/models/
    startCommand: |
      pwd
      ls -lh
      mkdir -p models
      # Use tar to preserve file attributes
      cd /opt/render/project/models && tar czf - skin_classifier_model.pth class_indices.npy | (cd /opt/render/project/src/skin-analyzer/backend && tar xzf -)
      # Verify files after copying
      ls -lh
      # Print file contents for debugging
      file skin_classifier_model.pth
      head -c 100 skin_classifier_model.pth | xxd
      python -c "import torch; print(f'PyTorch version: {torch.__version__}')"
      python -c "import numpy; print(f'NumPy version: {numpy.__version__}')"
      gunicorn --workers 1 --timeout 120 --log-level debug app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PORT
        value: 8000
      - key: PATH
        value: /opt/render/project/python/bin:${PATH}
      - key: PYTHONPATH
        value: /opt/render/project/python
      - key: PYTORCH_ENABLE_MPS_FALLBACK
        value: "1"
      - key: NUMPY_EXPERIMENTAL_ARRAY_FUNCTION
        value: "0"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: TORCH_HOME
        value: "/opt/render/project/.torch"
      - key: GITHUB_PAGES_URL
        value: https://murayeeto.github.io
      - key: UPLOAD_FOLDER
        value: /tmp/uploads
    autoDeploy: true